<div class="ProfSideBar">
    <table class="ProfSideBarTable">
        <ul class="ProfSideBarUl">
            <li class="ProfSideBarLi"><a href="profiel/bestellingen">Bestellingen</a></li>
            <li class="ProfSideBarLi"><a>testa</a></li>
            <li class="ProfSideBarLi"><a>testa</a></li>
            <li class="ProfSideBarLi"><a>testa</a></li>
            <li class="ProfSideBarLi"><a>testa</a></li>
        </ul>
    </table>
</div>