<!DOCTYPE html>
<html lang="nl">
    <head>
        <?php include config["TEMPLATE_FOLDER"] . "Head.phtml" ?>
        <link rel="stylesheet" href="css/Profile.css">
    </head>
    <body>
        <?php include config["TEMPLATE_FOLDER"] . "Header.phtml" ?>     <!--Import Header-->

        <!--Content↓↓-->
        <?php include config["TEMPLATE_FOLDER"] . "ProfileSideBar.phtml" ?>


        <!--Content↑↑-->

        <?php include config["TEMPLATE_FOLDER"] . "Footer.phtml" ?>     <!--Import Footer-->
    </body>
</html>
